packages:
  - "packages/*"
  - "apps/*"

catalog:
  react: "19.2.3"
  react-dom: "19.2.3"
  "@types/react": "^19.2.7"
  "@types/react-dom": "^19.2.3"
  "@types/node": "^20.19.0"
  typescript: "^5.4.5"
  vite: "^7.3.0"
  storybook: "10.1.10"
  "@storybook/react": "10.1.10"
  "@storybook/react-vite": "10.1.10"
  "@storybook/addon-essentials": "8.6.14"
  "@storybook/addon-links": "10.1.10"
  turbo: "^2.1.3"
  prettier: "^3.2.5"
  "@tailwindcss/postcss": "^4.1.10"
  "@types/eslint": "^8.56.5"
  autoprefixer: "^10.4.19"
  eslint: "^8.57.0"
  glob: "^11.0.3"
  postcss: "^8.4.38"
  "postcss-load-config": "^6.0.1"
  "react-hook-form": "^7.69.0"
  "tailwind-merge": "^2.3.0"
  tailwindcss: "^3.4.3"
  "tailwindcss-animate": "^1.0.7"
  tsup: "^8.3.0"