packages:
  - packages/*

catalog:
  '@hookform/resolvers': ^5.2.2
  '@mdx-js/loader': ^3.1.0
  '@mdx-js/react': ^3.1.0
  '@next/mdx': ^16.1.6
  '@storybook/addon-docs': 10.2.8
  '@storybook/react': 10.2.8
  '@storybook/react-vite': 10.2.8
  '@tailwindcss/postcss': ^4.1.10
  '@turbo/gen': ^2.8.3
  '@types/eslint': ^9.6.1
  '@types/node': ^25.2.2
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  ajv: 8.17.1
  ajv-formats: ^3.0.1
  autoprefixer: 10.4.24
  eslint: ^9.18.0
  eslint-plugin-storybook: ^0.11.3
  glob: ^11.0.7
  lucide-react: ^0.563.0
  next: ^16.1.6
  postcss: 8.5.6
  postcss-load-config: ^6.0.1
  prettier: ^3.8.1
  react: 19.2.4
  react-dom: 19.2.4
  react-hook-form: ^7.71.1
  storybook: 10.2.8
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.10
  tailwindcss-animate: ^1.0.7
  tsup: 8.5.1
  turbo: ^2.8.3
  typescript: ^5.4.5
  vite: ^7.3.1
